remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: La Palma - Observability Challenge
description: "Repositório dedicado à construção da estrutura para um desafio técnico, focando em conceitos de obsaervability"
