version: '3.8'
  
services:

  server:
    image: sample/server
    build:
      context: backend
      dockerfile: ../build
    ports:
      - 8080:8080      
    restart: unless-stopped 
    networks:
       server:

  node-exporter:
    image: prom/node-exporter:v1.7.0
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.systemd'
      - '--collector.processes'
    restart: unless-stopped 
    networks:
       server:

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    ports:
      - 8080:8080
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:ro'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
      - '/dev/disk/:/dev/disk:ro'
    devices:
      - '/dev/kmsg'
    restart: unless-stopped
    privileged: true
    networks:
       server:

networks:
  server:
     name: server